name: lint

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/lint.yaml'
      - '!docker/**'
      - '!docs/**'
      - '!contrib/**'

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install flake8 pep8-naming
      # ignore and ignore-names list as per setup.cfg
      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v1.0.1
        with:
          linters: flake8
          run: |
            flake8 . --exclude Dockerfile --ignore=E711,E226,W503,W504,E124,F841,W605 --ignore-names=W,H,A,S,R,T,WS,X,Y,Z,XX,YY,XY,B,M,N,L,NX,NY

  pylint:
    runs-on: ubuntu-latest
    name: Pylint
    steps:
      - name: checkout git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies and run pylint
        run: |
          sudo apt-get remove python3-openssl
          pip install --upgrade -e '.[test]'
          pylint -j 2 --reports no datacube


  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run pycodestyle
        run: |
          sudo apt-get remove python3-openssl
          pip install --upgrade -e '.[test]'
          pycodestyle tests integration_tests examples --max-line-length 120
