name: build

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/lint.yaml'
      - '!docker/**'
      - '!docs/**'
      - '!contrib/**'

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: |
            # ignore list as per setup.cfg
            flake8 . --exclude Dockerfile --ignore=E711,E226,W503,W504

  pylint:
    runs-on: ubuntu-latest
    name: Pylint
    steps:
      - name: checkout git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies and run pylint
        run: |
          pip install --upgrade -e '.[test]'
          pip install pylint
          pylint -j 2 --reports no datacube


  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install pycodestyle
      - name: pycodestyle
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: pycodestyle
          run: |
            pycodestyle tests integration_tests examples --max-line-length 120
